import type { Metadata } from "next";
import { Inter, Lusitana } from "next/font/google";
import Header from "./components/header/page";
import Footer from "./components/footer/page";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Raymond Negron",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
